### ISSUE TITLE
mesh check failed

### ISSUE THREAD

**Issue by nipinl** [damogranlabs/classy_blocks#15]
The mesh check failed for a few examples as I tried just now. airfoil_2d, elbow and pump_volute are failed at checkMesh.
elbow: ***Number of edges not aligned with or perpendicular to non-empty directions: 40110

**Comment by FranzBangar** [comment]
That's because the examples don't fully define every patch. BlockMesh sets defaultFaces (type empty) to block sides where patches are not specifically defined and checkMesh sees that as an 'error'. If you use mesh.set_default_patch() or manually add set_patch() on relevant block faces, this message will go away.

**Comment by nipinl** [comment]
Thanks !! I changed the type of defaultFaces to patch in constant/polyMesh/boundary in case then the checkMesh was success.
naming the patch (say, for example,  "chained.set_outer_patch('pipeWall')" for the case of elbow.py) is the best way, I think. Great work Nejc. I'll keep exploring this !!
