### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by GontzalLopez** [damogranlabs/classy_blocks#26]
* classy_blocks version:
* Python version: 3.8
* Operating System: Ubuntu 18.04 LTS

### Description

I'm getting the following error while installing:
        File "setup.py", line 6
          def read_file(rel_path: str) -> str:
                                ^
      SyntaxError: invalid syntax

### What I Did

 sudo python setup.py install

**Comment by GontzalLopez** [comment]
Yes, and the following error appear. I have to check the python version (the default is 3.8) but here is looking the 2.7 version folder.

![Screenshot from 2023-04-25 12-47-38](https://user-images.githubusercontent.com/61630172/234254576-d5f14136-3004-407f-a446-bed3800f0800.png)

**Comment by schperplata** [comment]
Hey @GontzalLopez, be sure you know the exact python you are using - seems to me like your `python` or `pip` command are defaulting to python 2.7. Based on your picture, that is also what the warning in the terminal show you. 

Try:
* Use absolute/exact path to python interpreter, instead of `python` or `py` command.
* Use `python -m pip install ...` as suggested above, if your chosen python Scripts directory is not on PATH.
* If you use virtual environment (you should for most use cases), make sure it is activated before plain `python` command is invoked.

... and report back. :)

**Comment by GontzalLopez** [comment]
Thanks @schperplata ! It finally works with:
`python3 -m pip install git+https://github.com/damogranlabs/classy_blocks.git`
